# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
# Type
"type: game server request":
    - '/(Server Request)/i'
"type: bug":
    - '/(bug)/i'
"type: feature request":
    - '/(feature)/i'
# Commands
"command: backup":
    - '/(backup)/i'
"command: console":
    - '/(console|tmux)/i'
"command: debug":
    - '/(debug)/i'
"command: details":
    - '/(details)/i'
"command: fast-dl":
    - '/(fast-dl|fastdl)/i'
"command: install":
    - '/(install)/i'
"command: mods":
    - '/(mods)/i'
"command: monitor":
    - '/(monitor)/i'
"command: post-details":
    - '/(post-details)/i'
"command: restart":
    - '/(restart)/i'
"command: send":
    - '/(send)/i'
"command: skeleton":
    - '/(skeleton)/i'
"command: start":
    - '/(start)/i'
"command: stop":
    - '/(stop)/i'
"command: update-lgsm":
    - '/(update-lgsm)/i'
"command: update":
    - '/(update)/i'
"command: validate":
    - '/(validate)/i'
"command: wipe":
    - '/(wipe)/i'
# Distros
"distro: AlmaLinux":
    - '/(Alma)/i'
"distro: Arch Linux":
    - '/(Arch)/i'
"distro: CentOS":
    - '/(CentOS)/i'
"distro: Debian":
    - '/(Debian)/i'
"distro: Fedora":
    - '/(Fedora)/i'
"distro: openSUSE":
    - '/(openSUSE|suse)/i'
"distro: Rocky Linux":
    - '/(Rocky)/i'
"distro: Slackware":
    - '/(Slackware)/i'
"distro: Ubuntu":
    - '/(Ubuntu)/i'
# Info
"info: alerts":
    - '/(alert)/i'
"info: dependency":
    - '/(dependency|deps)/i'
"info: docker":
    - '/(docker)/i'
"info: docs":
    - '/(documentation|docs)/i'
"info: email":
    - '/(postfix|sendmail|exim|smtp)/i'
"info: steamcmd":
    - '/(steamcmd)/i'
"info: systemd":
    - '/(systemd)/i'
"info: tmux":
    - '/(tmux)/i'
"info: website":
    - '/(website)/i'
