#!/bin/bash
# LGSM fn_install_serverfiles function
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
# Version: 160515

if [ -z "${steamuser}" ]; then
        fn_printwarningnl "SteamCMD user variable is not assigned in the main script! Resorting to anonymous login"
	steamuser="anonymous"
	steampass=""
fi
