#!/bin/bash
# LGSM fn_check_ip function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 210115

# Description: Automatically identifies the server interface IP.
# If multiple interfaces are detected the user will need to manualy set using ip="0.0.0.0".

getip=$(hostname -I)

if [ "${ip}" == "0.0.0.0" ]||[ "${ip}" == "" ]; then
	ip=${getip}
fi

