#!/bin/bash
# LGSM fn_check_root function
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
# Version: 210115

if [ $(whoami) = "root" ]; then
	fn_printfailnl "Do NOT run this script as root!"
	exit
fi