#!/bin/bash
# LGSM fn_check_steamuser function
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
# Version: 190515

if [ -z "${steamuser}" ]||[ "${steamuser}" == "username" ]; then
		fn_printwarnnl "Steam login not set. Using anonymous login."
		fn_scriptlog "Steam Login not set. Using anonymous login."
		if [ "${steamuser}" == "username" ]; then
			echo "	* Change steamuser=\"username\" to a valid steam login."
			fn_scriptlog "Change steamuser=\"username\" to a valid steam login."
		fi
		steamuser="anonymous"
		steampass=""
		sleep 2
fi
