#!/bin/bash
# LGSM fn_emailtest function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 010115

# Description: Sends a test email notification.

local modulename="Email"
fn_rootcheck
fn_syscheck
if [ "${emailnotification}" = "on" ]; then
	fn_scriptlog "Sending test notification"
	subject="${servicename} Email Test Notification - Testing ${servername}"
	failurereason="Testing ${servicename} email notification"
	actiontaken="Sent test email...hello is this thing on?"
	fn_emailnotification
else
	fn_printfailnl "Notifications not enabled"
	fn_scriptlog "Notifications not enabled"
fi