#!/bin/bash
# LGSM fn_email_test function
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
lgsm_version="061115"

# Description: Sends a test email notification.

local modulename="Email"
fn_check_root
fn_check_systemdir
fn_details_config
if [ "${emailnotification}" = "on" ]; then
	fn_scriptlog "Sending test notification"
	subject="${servicename} Email Test Notification - Testing ${servername}"
	failurereason="Testing ${servicename} email notification"
	actiontaken="Sent test email...hello is this thing on?"
	fn_email
else
	fn_printfailnl "Notifications not enabled"
	fn_scriptlog "Notifications not enabled"
fi