#!/bin/bash
# LGSM fn_functions function
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
lgsm_version="261215"

# Description: Redirect to new core_functions.sh

core_functions.sh(){
# Functions are defined in fn_functions.
functionfile="${FUNCNAME}"
fn_runfunction
}

fn_getopt(){
functionfile="${FUNCNAME}"
fn_runfunction
}
