#!/bin/bash
# LGSM fn_fninstall function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 021114

cd functions
#fn_glibcfix
wget https://raw.githubusercontent.com/dgibbs64/linuxgameservers/master/functions/fn_glibcfix
chmod +x fn_glibcfix