#!/bin/bash
# LGSM fn_getquery function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 231214

fn_dlgsquery(){
cd "${rootdir}"
echo -e "downloading lgsm-default.cfg...\c"
wget --no-check-certificate /dev/null "http://danielgibbs.co.uk/dl/gsquery.py" 2>&1 | grep -F "HTTP" | grep -v "Moved Permanently" | cut -c45-
chmod +x gsquery.py
}

echo ""
echo "GameServerQuery"
echo "============================"
if [ -z ${autoinstall} ]; then
	while true; do
		read -p "Do you want to install GameServerQuery? [y/N]" yn
		case $yn in
		[Yy]* ) fn_dlgsquery;break;;
		[Nn]* ) echo ""; echo "Not installing GameServerQuery.";break;;
		* ) echo "Please answer yes or no.";;
	esac
	done
else
	fn_dlgsquery
fi