#!/bin/bash
# LGSM fn_install_header function
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
lgsm_version="061115"

clear
echo "================================="
echo "${gamename}"
echo "Linux Game Server Manager"
echo "by Daniel Gibbs"
if [ "${gamename}" == "ARMA 3" ]; then
	echo "contributions by Scarsz"
elif [ "${gamename}" == "Left 4 Dead" ]; then
	echo "contributions by Summit Singh Thakur"
fi
echo "http://gameservermanagers.com"
echo "================================="