#!/bin/bash
# LGSM fn_installcomplete function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 241214

echo "================================="
echo "Install Complete!"
echo ""
echo "To start server type:"
echo "${selfname} start"
echo ""