#!/bin/bash
# LGSM fn_install_retry function
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
# Version: 210115
lgsm_version="061115"


while true; do
	read -p "Retry install? [y/N]" yn
	case $yn in
	[Yy]* ) fn_install; exit;;
	[Nn]* ) echo Exiting; exit;;
	* ) echo "Please answer yes or no.";;
	esac
done