#!/bin/bash
# LGSM fn_install_steamfix function
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
lgsm_version="061115"

fn_steamclientfix(){
echo ""
echo "Applying steamclient.so fix"
echo "================================="
sleep 1
mkdir -pv "${HOME}/.steam"
mkdir -pv "${HOME}/.steam/sdk32"
cp -v "${rootdir}/steamcmd/linux32/steamclient.so" "${HOME}/.steam/sdk32/steamclient.so"
	if [[ $? != 0 ]]; then
		fn_printfailurenl "Cannot start apply steamclient.so fix."
	fi	
sleep 1
}

# Gary's Mod Specific
fn_libsteamfix(){
echo ""
echo "Applying libsteam.so fix"
echo "================================="
sleep 1
mkdir -pv "${HOME}/.steam"
mkdir -pv "${HOME}/.steam/sdk32"
if [ "${gamename}" == "Garry's Mod" ]; then
	cp -v "${filesdir}/bin/libsteam.so" "${HOME}/.steam/sdk32/libsteam.so"
elif [ "${gamename}" == "Serious Sam 3: BFE" ]; then
	mkdir "${HOME}/.steam/bin32"
	cp -v "${filesdir}/Bin/libsteam.so" "${HOME}/.steam/bin32/libsteam.so"
fi
if [[ $? != 0 ]]; then
	fn_printfailurenl "Cannot start apply libsteam.so fix."
fi	
sleep 1
}

fn_steamclientfix
if [ "${gamename}" == "Garry's Mod" ]||[ "${gamename}" == "Serious Sam 3: BFE" ]; then
	fn_libsteamfix
fi
