#!/bin/bash
# LGSM fn_loginstall function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 241214

echo ""
echo "Creating log directorys"
echo "================================="
sleep 1
# Create dir's for the script and console logs
mkdir -v "${rootdir}/log"
mkdir -v "${scriptlogdir}"
touch "${scriptlog}"
mkdir -v "${consolelogdir}"
touch "${consolelog}"
# If a server is source or goldsource create a symbolic link to the game server logs
if [ "${engine}" == "source" ]||[ "${engine}" == "goldsource" ]; then
	if [ ! -h ${rootdir}/log/server ]; then
		ln -sv "${gamelogdir}" "${rootdir}/log/server"
	else
		echo "Symbolic link ${gamelogdir} => ${rootdir}/log/server already exists!"
	fi
fi
# If a server is unreal2 or unity3d create a dir
if [ "${engine}" == "unreal2" ]||[ "${engine}" == "unity3d" ]; then
	mkdir -pv ${gamelogdir}
fi
if [ "${gamename}" == "7 Days To Die" ]; then
	ln -sv "${filesdir}/7DaysToDie_Data/output_log.txt" "${gamelogdir}/output_log.txt"
fi
sleep 1