#!/bin/bash
# LGSM fn_load function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 141214
# Depricated: fn_distrodetails has replaced this function.

load=$(uptime|awk -F 'load average' '{ print $2 }')