#!/bin/bash
# LGSM fn_rootcheck function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 241214

if [ $(whoami) = "root" ]; then
	fn_printfailnl "Do NOT run this script as root!"
	exit
fi