#!/bin/bash
# LGSM fn_steamdl function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 231114

echo "Installing SteamCMD"
echo "================================="
cd "${rootdir}"
mkdir -pv "steamcmd"
sleep 1
cd "steamcmd"
if [ ! -f steamcmd.sh ]; then
	wget -nv -N http://media.steampowered.com/client/steamcmd_linux.tar.gz
	tar --verbose -zxf steamcmd_linux.tar.gz
	rm -v steamcmd_linux.tar.gz
	chmod +x steamcmd.sh
	sleep 1
else
	echo "Steam already installed!"
fi
sleep 1
echo ""