#!/bin/bash
# LGSM fn_sdtdfix_alloc function
# Author: Daniel Gibbs
# Contributor: Chris Koepf
# Website: http://gameservermanagers.com
# Version: 210115

# Description: Creates a .tar.gz file in the backup directory.
# addition for 7 Days to Die - very popular server addon run on most dedicated servers
# file validation breaks this addon and it requires re-installation each time.

if [ "${allocsfixes}" = true ]; then
        sleep 5
        fn_scriptlog "Installing Alloc's Server Fixes"
        echo -en "\n"
        sleep 5
        echo -en "Installing Alloc's Server Fixes\n"
        cd "${rootdir}"/serverfiles/
        rm -rf server_fixes.tar.gz
        wget http://illy.bz/fi/7dtd/server_fixes.tar.gz
        if [ -f "server_fixes.tar.gz" ]; then
                tar -xzf server_fixes.tar.gz
                rm -rf server_fixes.tar.gz
                fn_scriptlog "Server Fixes Installed"
                echo -en "Alloc's Server Fixes have been installed.\n"
        else
            	if [ ! -f "server_fixes.tar.gz" ]; then
                        fn_scriptlog "Error downloading Server Fixes!"
                fi
                echo -en "There was a problem installing Alloc's Server Fixes!"
        fi

	fn_scriptlog "Alloc's Server Fixes installed."
        echo -en "FAlloc's Server Fixes installed.\n"
fi
}