#!/bin/bash
# LGSM fn_serverdirectory function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 010115

echo ""
echo "Server Directory"
echo "================================="
echo ""
pwd
echo ""
if [ -d "${filesdir}" ]; then
	fn_printwarningnl "A server is already installed here."
fi
while true; do
	read -p "Continue [y/N]" yn
	case $yn in
	[Yy]* ) break;;
	[Nn]* ) echo Exiting; return 1;;
	* ) echo "Please answer yes or no.";;
	esac
done