#!/bin/bash
# LGSM fn_serverdirectory function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 011214

echo "Server Directory"
echo "================================="
echo ""
pwd
echo ""
if [ -d "${filesdir}" ]; then
	echo -e "\e[0;31mWARNING!\e[0;39m A server is already installed here"
fi
while true; do
	read -p "Continue [y/N]" yn
	case $yn in
	[Yy]* ) break;;
	[Nn]* ) echo Exiting; return 1;;
	* ) echo "Please answer yes or no.";;
	esac
done