#!/bin/bash
# LGSM fn_ut99fix function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 011214

echo "Applying ${gamename} Server Fixes"
echo "================================="
echo "enabling UdpServerUplink."
{
echo "[IpServer.UdpServerUplink]"
echo "DoUplink=True"
echo "UpdateMinutes=1"
echo "MasterServerAddress=unreal.epicgames.com"
echo "MasterServerPort=27900"
echo "Region=0"
}|tee -a "${systemdir}/${ini}" > /dev/null 2>&1
sleep 1
echo "removing dead mplayer.com master server."
sed -i '/master.mplayer.com/d' "${systemdir}/${ini}"
sleep 1
echo "inserting qtracker.com master server."
sed -i '66i\ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.qtracker.com MasterServerPort=27900' "${systemdir}/${ini}"
echo ""