#!/bin/bash
# LGSM fn_update_functions.sh function
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
lgsm_version="230116"

# Description: LEGACY FUNCTION Deletes the functions dir to allow re-downloading of functions from GitHub.

fn_print_dots "Updating functions"
fn_scriptlog "Updating functions"
sleep 1
echo -ne "\n"
rm -rfv "${rootdir}/functions/"*
exitcode=$?
if [ "${exitcode}" == "0" ]; then
	fn_print_ok "Updating functions"
	fn_scriptlog "Success! Updating functions"
else
	fn_print_fail "Updating functions"
	fn_scriptlog "Failure! Updating functions"
fi
echo -ne "\n"