#!/bin/bash
# LGSM fn_updateserver function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 010115

# Description: Runs a server update.

local modulename="Update"
fn_rootcheck
fn_syscheck
fn_printdots "Updating ${servername}"
sleep 1
fn_printok "Updating ${servername}"
fn_scriptlog "Updating ${servername}"
sleep 1
cd "${rootdir}"
cd "steamcmd"
./steamcmd.sh +login "${steamuser}" "${steampass}" +force_install_dir "${filesdir}" +app_update "${appid}" +quit|tee -a "${scriptlog}"
