#!/bin/bash
# LGSM fn_update_dl function
# Author: Daniel Gibbs
# Website: http://danielgibbs.co.uk
# Version: 210115

# Description: Runs a server update.

local modulename="Update"
fn_check_root
fn_check_systemdir
fn_details_config
fn_printdots "Updating ${servername}"
sleep 1
fn_check_steamcmd
fn_printoknl "Updating ${servername}"
fn_scriptlog "Updating ${servername}"
sleep 1
cd "${rootdir}"
cd "steamcmd"
./steamcmd.sh +login "${steamuser}" "${steampass}" +force_install_dir "${filesdir}" +app_update "${appid}" +quit|tee -a "${scriptlog}"
