#!/bin/bash
# LGSM core_functions.sh function
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
lgsm_version="271215"

# Description: Redirect to new core_functions.sh

core_functions.sh(){
# Functions are defined in core_functions.sh.
functionfile="${FUNCNAME}"
fn_runfunction
}

core_dl.sh(){
# Functions are defined in core_functions.sh.
functionfile="${FUNCNAME}"
fn_runfunction
}

core_getopt.sh(){
functionfile="${FUNCNAME}"
fn_runfunction
}

core_messages.sh(){
functionfile="${FUNCNAME}"
fn_runfunction
}

command_update_functions.sh(){
functionfile="${FUNCNAME}"
fn_runfunction
}

core_functions.sh
command_update_functions.sh

