#!/bin/bash
# LGSM fn_functions function
# Author: Daniel Gibbs
# Website: https://gameservermanagers.com
lgsm_version="211016"

# Description: Redirects to new core_functions.sh

core_functions.sh(){
# Functions are defined in core_functions.sh.
functionfile="${FUNCNAME}"
fn_runfunction
}

core_getopt.sh(){
functionfile="${FUNCNAME}"
fn_runfunction
}

core_functions.sh