#!/bin/bash
# LGSM core_functions.sh function
# Author: Daniel Gibbs
# Website: https://gameservermanagers.com
lgsm_version="210516"

# Description: Redirect to new core_functions.sh

core_functions.sh(){
# Functions are defined in core_functions.sh.
functionfile="${FUNCNAME}"
fn_runfunction
}

core_getopt.sh(){
functionfile="${FUNCNAME}"
fn_runfunction
}

core_functions.sh