#!/bin/bash
# LGSM fn_getopt function
# Author: Daniel Gibbs
# Website: https://gameservermanagers.com
lgsm_version="210516"

# Description: Redirect to new core_getopt.sh

core_getopt.sh(){
# Functions are defined in core_functions.sh.
functionfile="${FUNCNAME}"
fn_runfunction
}

core_getopt.sh