name: Version Check
on:
  push:

permissions:
  contents: read

jobs:
  version-Check:
    if: github.repository_owner == 'GameServerManagers'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version Check
        run: .github/scripts/version-check.sh
