name: Server list Validation
on:
  workflow_dispatch:
  push:

jobs:
  serverlist-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: compare versions
        run: chmod +x .github/workflows/serverlist-validate.sh; .github/workflows/serverlist-validate.sh
